(ns hyperopen.portfolio.optimizer.contracts.paths)

(def optimizer-path [:portfolio :optimizer])
(def draft-path (conj optimizer-path :draft))
(def draft-id-path (conj draft-path :id))
(def draft-name-path (conj draft-path :name))
(def draft-status-path (conj draft-path :status))
(def draft-universe-path (conj draft-path :universe))
(def draft-objective-path (conj draft-path :objective))
(def draft-return-model-path (conj draft-path :return-model))
(def draft-return-model-views-path (conj draft-return-model-path :views))
(def draft-risk-model-path (conj draft-path :risk-model))
(def draft-constraints-path (conj draft-path :constraints))
(def draft-execution-assumptions-path (conj draft-path :execution-assumptions))
(def draft-metadata-path (conj draft-path :metadata))
(def draft-dirty-path (conj draft-metadata-path :dirty?))
(def active-scenario-path (conj optimizer-path :active-scenario))
(def active-scenario-loaded-id-path (conj active-scenario-path :loaded-id))
(def active-scenario-name-path (conj active-scenario-path :name))
(def active-scenario-status-path (conj active-scenario-path :status))
(def active-scenario-read-only-path (conj active-scenario-path :read-only?))
(def run-state-path (conj optimizer-path :run-state))
(def run-state-status-path (conj run-state-path :status))
(def runtime-path (conj optimizer-path :runtime))
(def runtime-as-of-ms-path (conj runtime-path :as-of-ms))
(def runtime-stale-after-ms-path (conj runtime-path :stale-after-ms))
(def runtime-funding-periods-per-year-path
  (conj runtime-path :funding-periods-per-year))
(def runtime-orderbook-stale-after-ms-path
  (conj runtime-path :orderbook-stale-after-ms))
(def history-data-path (conj optimizer-path :history-data))
(def market-cap-by-coin-path (conj optimizer-path :market-cap-by-coin))
(def history-load-state-path (conj optimizer-path :history-load-state))
(def history-load-state-status-path (conj history-load-state-path :status))
(def history-load-state-request-signature-path
  (conj history-load-state-path :request-signature))
(def history-prefetch-path (conj optimizer-path :history-prefetch))
(def history-prefetch-active-instrument-id-path
  (conj history-prefetch-path :active-instrument-id))
(def optimization-progress-path (conj optimizer-path :optimization-progress))
(def optimization-progress-status-path (conj optimization-progress-path :status))
(def scenario-index-path (conj optimizer-path :scenario-index))
(def scenario-save-state-path (conj optimizer-path :scenario-save-state))
(def scenario-load-state-path (conj optimizer-path :scenario-load-state))
(def scenario-index-load-state-path (conj optimizer-path :scenario-index-load-state))
(def scenario-archive-state-path (conj optimizer-path :scenario-archive-state))
(def scenario-duplicate-state-path (conj optimizer-path :scenario-duplicate-state))
(def last-successful-run-path (conj optimizer-path :last-successful-run))
(def last-successful-run-result-path (conj last-successful-run-path :result))
(def execution-modal-path (conj optimizer-path :execution-modal))
(def execution-modal-error-path (conj execution-modal-path :error))
(def execution-modal-submitting-path (conj execution-modal-path :submitting?))
(def execution-path (conj optimizer-path :execution))
(def execution-history-path (conj execution-path :history))
(def execution-persistence-error-path (conj execution-path :persistence-error))
(def tracking-path (conj optimizer-path :tracking))
(def tracking-error-path (conj tracking-path :error))
(def optimizer-ui-path [:portfolio-ui :optimizer])
(def ui-list-filter-path (conj optimizer-ui-path :list-filter))
(def ui-list-sort-path (conj optimizer-ui-path :list-sort))
(def ui-workspace-panel-path (conj optimizer-ui-path :workspace-panel))
(def ui-results-tab-path (conj optimizer-ui-path :results-tab))
(def ui-diagnostics-tab-path (conj optimizer-ui-path :diagnostics-tab))
(def ui-universe-search-query-path (conj optimizer-ui-path :universe-search-query))
(def ui-universe-search-active-index-path
  (conj optimizer-ui-path :universe-search-active-index))
(def ui-black-litterman-editor-path
  (conj optimizer-ui-path :black-litterman-editor))
(def ui-frontier-overlay-mode-path
  (conj optimizer-ui-path :frontier-overlay-mode))
(def ui-constrain-frontier-path (conj optimizer-ui-path :constrain-frontier?))
